

site_name: Olimex Documentation

repo_url: https://github.com/OLIMEX/documentation
repo_name: Github

site_author: "Olimex team"
google_analytics: ['UA-284946-9', 'docs.olimex.com']

theme: readthedocs
theme_dir: readthedocs_custom

markdown_extensions:
  - smarty
  - footnotes
  - toc:
      permalink: True

pages:
  - Home: index.md

  - 'Changelog' : 'Release_Changelog.md'

  - 'User Guide' :
        - 'Getting Started' : 'User-Guide_Getting-Started.md'
        - 'Quick facts' : 'Quick_facts.md'
        - 'Troubleshooting' : 'User-Guide_Basic-Troubleshooting.md'
        - 'Advanced Features' : 'User-Guide_Advanced-Features.md'
        - 'Fine Tuning' : 'User-Guide_Fine-Tuning.md'
        - 'Olimex config' : 'User-Guide_Olimex-Config.md'
        - 'Allwinner DT overlays' : 'User-Guide_Allwinner_overlays.md'
        - 'Migration from Bananian' : 'User-Guide_Migration_from_Bananian.md'

  - 'Hardware Notes' :
        - 'Allwinner (Generic)' : 'Hardware_Allwinner.md'
        - 'A10 and A20' : 'Hardware_Allwinner-A20.md'
        - 'H2+ and H3' : 'Hardware_Allwinner-H3.md'
        - 'H5 and A64' : 'Hardware_Allwinner-H5-A64.md'
        - 'Freescale i.MX6' : 'Hardware_Freescale-imx6.md'
        - 'Marvell Armada' : 'Hardware_Marvell.md'

  - 'Developer Guide' :
        - 'Building Olimex' : 'Developer-Guide_Build-Preparation.md'
        - 'Building with Vagrant' : 'Developer-Guide_Using-Vagrant.md'
        - 'Building with Docker': 'Developer-Guide_Building-with-Docker.md'
        - 'Build Options' : 'Developer-Guide_Build-Options.md'
        - 'User Configurations' : 'Developer-Guide_User-Configurations.md'
        - 'FEL boot' : 'Developer-Guide_FEL-boot.md'

  - 'Contributor Process' :
        - 'Contribute' : 'Process_Contribute.md'
        - 'Documentation' : 'Process_Documentation.md'
